---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("rest_inspec")


rest_insp = 
  rest_inspec %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  select(-camis, -phone, -record_date, -grade_date) 

nyc_rest = 
  rest_insp %>% 
  sample_frac(size = .1)



```
I excluded pending grades and information where the borough is missing 


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r Boxplot}

nyc_rest %>% 
  separate(inspection_date, into = c("year", "month", "day")) %>% 
  plot_ly(y = ~score, color = ~year, type = "box", colors = "viridis")

nyc_rest %>% 
  separate(inspection_date, into = c("year", "month", "day")) %>% 
  plot_ly(y = ~score, color = ~year, type = "violin", colors = "viridis")


nyc_rest %>% 
  mutate(cuisine = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "violin", colors = "viridis")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r Scatterplot}

nyc_rest %>%
  plot_ly(
    x = ~inspection_date, y = ~score, type = "scatter", mode = "markers",
    color = ~boro, text = ~violation_description, alpha = 0.5, colors = "viridis")

```




### Chart C

```{r}
nyc_rest %>%   
  separate(inspection_date, into = c("year", "month", "day")) %>% 
  count(year) %>% 
  mutate(year = fct_reorder(year, n)) %>% 
  plot_ly(x = ~year, y = ~n, color = ~year, type = "bar", colors = "viridis")


```




